import moment from "moment-timezone";
import React, { useEffect, useState } from "react";


const countries = [
  { country: "Afghanistan", timeZone: "Asia/Kabul" },
  { country: "Albania", timeZone: "Europe/Tirane" },
  { country: "Algeria", timeZone: "Africa/Algiers" },
  { country: "Andorra", timeZone: "Europe/Andorra" },
  { country: "Angola", timeZone: "Africa/Luanda" },
  { country: "Antigua and Barbuda", timeZone: "America/Antigua" },
  { country: "Argentina", timeZone: "America/Argentina/Buenos_Aires" },
  { country: "Armenia", timeZone: "Asia/Yerevan" },
  { country: "Australia", timeZone: "Australia/Sydney" },
  { country: "Austria", timeZone: "Europe/Vienna" },
  { country: "Azerbaijan", timeZone: "Asia/Baku" },
  { country: "Bahamas", timeZone: "America/Nassau" },
  { country: "Bahrain", timeZone: "Asia/Bahrain" },
  { country: "Bangladesh", timeZone: "Asia/Dhaka" },
  { country: "Barbados", timeZone: "America/Barbados" },
  { country: "Belarus", timeZone: "Europe/Minsk" },
  { country: "Belgium", timeZone: "Europe/Brussels" },
  { country: "Belize", timeZone: "America/Belize" },
  { country: "Benin", timeZone: "Africa/Porto-Novo" },
  { country: "Bhutan", timeZone: "Asia/Thimphu" },
  { country: "Bolivia", timeZone: "America/La_Paz" },
  { country: "Bosnia and Herzegovina", timeZone: "Europe/Sarajevo" },
  { country: "Botswana", timeZone: "Africa/Gaborone" },
  { country: "Brazil", timeZone: "America/Sao_Paulo" },
  { country: "Brunei", timeZone: "Asia/Brunei" },
  { country: "Bulgaria", timeZone: "Europe/Sofia" },
  { country: "Burkina Faso", timeZone: "Africa/Ouagadougou" },
  { country: "Burundi", timeZone: "Africa/Bujumbura" },
  { country: "Cambodia", timeZone: "Asia/Phnom_Penh" },
  { country: "Cameroon", timeZone: "Africa/Douala" },
  { country: "Canada", timeZone: "America/Toronto" },
  { country: "Cape Verde", timeZone: "Atlantic/Cape_Verde" },
  { country: "Central African Republic", timeZone: "Africa/Bangui" },
  { country: "Chad", timeZone: "Africa/Ndjamena" },
  { country: "Chile", timeZone: "America/Santiago" },
  { country: "China", timeZone: "Asia/Shanghai" },
  { country: "Colombia", timeZone: "America/Bogota" },
  { country: "Comoros", timeZone: "Africa/Moroni" },
  { country: "Congo (Democratic Republic)", timeZone: "Africa/Kinshasa" },
  { country: "Congo (Republic)", timeZone: "Africa/Brazzaville" },
  { country: "Costa Rica", timeZone: "America/Costa_Rica" },
  { country: "Croatia", timeZone: "Europe/Zagreb" },
  { country: "Cuba", timeZone: "America/Havana" },
  { country: "Cyprus", timeZone: "Asia/Nicosia" },
  { country: "Czech Republic", timeZone: "Europe/Prague" },
  { country: "Denmark", timeZone: "Europe/Copenhagen" },
  { country: "Djibouti", timeZone: "Africa/Djibouti" },
  { country: "Dominica", timeZone: "America/Dominica" },
  { country: "Dominican Republic", timeZone: "America/Santo_Domingo" },
  { country: "Ecuador", timeZone: "America/Guayaquil" },
  { country: "Egypt", timeZone: "Africa/Cairo" },
  { country: "El Salvador", timeZone: "America/El_Salvador" },
  { country: "Equatorial Guinea", timeZone: "Africa/Malabo" },
  { country: "Eritrea", timeZone: "Africa/Asmara" },
  { country: "Estonia", timeZone: "Europe/Tallinn" },
  { country: "Eswatini", timeZone: "Africa/Mbabane" },
  { country: "Ethiopia", timeZone: "Africa/Addis_Ababa" },
  { country: "Fiji", timeZone: "Pacific/Fiji" },
  { country: "Finland", timeZone: "Europe/Helsinki" },
  { country: "France", timeZone: "Europe/Paris" },
  { country: "Gabon", timeZone: "Africa/Libreville" },
  { country: "Gambia", timeZone: "Africa/Banjul" },
  { country: "Georgia", timeZone: "Asia/Tbilisi" },
  { country: "Germany", timeZone: "Europe/Berlin" },
  { country: "Ghana", timeZone: "Africa/Accra" },
  { country: "Greece", timeZone: "Europe/Athens" },
  { country: "Grenada", timeZone: "America/Grenada" },
  { country: "Guatemala", timeZone: "America/Guatemala" },
  { country: "Guinea", timeZone: "Africa/Conakry" },
  { country: "Guinea-Bissau", timeZone: "Africa/Bissau" },
  { country: "Guyana", timeZone: "America/Guyana" },
  { country: "Haiti", timeZone: "America/Port-au-Prince" },
  { country: "Honduras", timeZone: "America/Tegucigalpa" },
  { country: "Hungary", timeZone: "Europe/Budapest" },
  { country: "Iceland", timeZone: "Atlantic/Reykjavik" },
  { country: "India", timeZone: "Asia/Kolkata" },
  { country: "Indonesia", timeZone: "Asia/Jakarta" },
  { country: "Iran", timeZone: "Asia/Tehran" },
  { country: "Iraq", timeZone: "Asia/Baghdad" },
  { country: "Ireland", timeZone: "Europe/Dublin" },
  { country: "Israel", timeZone: "Asia/Jerusalem" },
  { country: "Italy", timeZone: "Europe/Rome" },
  { country: "Jamaica", timeZone: "America/Jamaica" },
  { country: "Japan", timeZone: "Asia/Tokyo" },
  { country: "Jordan", timeZone: "Asia/Amman" },
  { country: "Kazakhstan", timeZone: "Asia/Almaty" },
  { country: "Kenya", timeZone: "Africa/Nairobi" },
  { country: "Kiribati", timeZone: "Pacific/Tarawa" },
  { country: "Kuwait", timeZone: "Asia/Kuwait" },
  { country: "Kyrgyzstan", timeZone: "Asia/Bishkek" },
  { country: "Laos", timeZone: "Asia/Vientiane" },
  { country: "Latvia", timeZone: "Europe/Riga" },
  { country: "Lebanon", timeZone: "Asia/Beirut" },
  { country: "Lesotho", timeZone: "Africa/Maseru" },
  { country: "Liberia", timeZone: "Africa/Monrovia" },
  { country: "Libya", timeZone: "Africa/Tripoli" },
  { country: "Liechtenstein", timeZone: "Europe/Vaduz" },
  { country: "Lithuania", timeZone: "Europe/Vilnius" },
  { country: "Luxembourg", timeZone: "Europe/Luxembourg" },
  { country: "Madagascar", timeZone: "Indian/Antananarivo" },
  { country: "Malawi", timeZone: "Africa/Blantyre" },
  { country: "Malaysia", timeZone: "Asia/Kuala_Lumpur" },
  { country: "Maldives", timeZone: "Indian/Maldives" },
  { country: "Mali", timeZone: "Africa/Bamako" },
  { country: "Malta", timeZone: "Europe/Malta" },
  { country: "Marshall Islands", timeZone: "Pacific/Majuro" },
  { country: "Mauritania", timeZone: "Africa/Nouakchott" },
  { country: "Mauritius", timeZone: "Indian/Mauritius" },
  { country: "Mexico", timeZone: "America/Mexico_City" },
  { country: "Micronesia", timeZone: "Pacific/Pohnpei" },
  { country: "Moldova", timeZone: "Europe/Chisinau" },
  { country: "Monaco", timeZone: "Europe/Monaco" },
  { country: "Mongolia", timeZone: "Asia/Ulaanbaatar" },
  { country: "Montenegro", timeZone: "Europe/Podgorica" },
  { country: "Morocco", timeZone: "Africa/Casablanca" },
  { country: "Mozambique", timeZone: "Africa/Maputo" },
  { country: "Myanmar", timeZone: "Asia/Yangon" },
  { country: "Namibia", timeZone: "Africa/Windhoek" },
  { country: "Nauru", timeZone: "Pacific/Nauru" },
  { country: "Nepal", timeZone: "Asia/Kathmandu" },
  { country: "Netherlands", timeZone: "Europe/Amsterdam" },
  { country: "New Zealand", timeZone: "Pacific/Auckland" },
  { country: "Nicaragua", timeZone: "America/Managua" },
  { country: "Niger", timeZone: "Africa/Niamey" },
  { country: "Nigeria", timeZone: "Africa/Lagos" },
  { country: "North Korea", timeZone: "Asia/Pyongyang" },
  { country: "North Macedonia", timeZone: "Europe/Skopje" },
  { country: "Norway", timeZone: "Europe/Oslo" },
  { country: "Oman", timeZone: "Asia/Muscat" },
  { country: "Pakistan", timeZone: "Asia/Karachi" },
  { country: "Palau", timeZone: "Pacific/Palau" },
  { country: "Panama", timeZone: "America/Panama" },
  { country: "Papua New Guinea", timeZone: "Pacific/Port_Moresby" },
  { country: "Paraguay", timeZone: "America/Asuncion" },
  { country: "Peru", timeZone: "America/Lima" },
  { country: "Philippines", timeZone: "Asia/Manila" },
  { country: "Poland", timeZone: "Europe/Warsaw" },
  { country: "Portugal", timeZone: "Europe/Lisbon" },
  { country: "Qatar", timeZone: "Asia/Qatar" },
  { country: "Romania", timeZone: "Europe/Bucharest" },
  { country: "Russia", timeZone: "Europe/Moscow" },
  { country: "Rwanda", timeZone: "Africa/Kigali" },
  { country: "Saint Lucia", timeZone: "America/St_Lucia" },
  { country: "Samoa", timeZone: "Pacific/Apia" },
  { country: "San Marino", timeZone: "Europe/San_Marino" },
  { country: "Saudi Arabia", timeZone: "Asia/Riyadh" },
  { country: "Senegal", timeZone: "Africa/Dakar" },
  { country: "Serbia", timeZone: "Europe/Belgrade" },
  { country: "Seychelles", timeZone: "Indian/Mahe" },
  { country: "Sierra Leone", timeZone: "Africa/Freetown" },
  { country: "Singapore", timeZone: "Asia/Singapore" },
  { country: "Slovakia", timeZone: "Europe/Bratislava" },
  { country: "Slovenia", timeZone: "Europe/Ljubljana" },
  { country: "Solomon Islands", timeZone: "Pacific/Guadalcanal" },
  { country: "Somalia", timeZone: "Africa/Mogadishu" },
  { country: "South Africa", timeZone: "Africa/Johannesburg" },
  { country: "South Korea", timeZone: "Asia/Seoul" },
  { country: "South Sudan", timeZone: "Africa/Juba" },
  { country: "Spain", timeZone: "Europe/Madrid" },
  { country: "Sri Lanka", timeZone: "Asia/Colombo" },
  { country: "Sudan", timeZone: "Africa/Khartoum" },
  { country: "Suriname", timeZone: "America/Paramaribo" },
  { country: "Sweden", timeZone: "Europe/Stockholm" },
  { country: "Switzerland", timeZone: "Europe/Zurich" },
  { country: "Syria", timeZone: "Asia/Damascus" },
  { country: "Taiwan", timeZone: "Asia/Taipei" },
  { country: "Tajikistan", timeZone: "Asia/Dushanbe" },
  { country: "Tanzania", timeZone: "Africa/Dar_es_Salaam" },
  { country: "Thailand", timeZone: "Asia/Bangkok" },
  { country: "Togo", timeZone: "Africa/Lome" },
  { country: "Tonga", timeZone: "Pacific/Tongatapu" },
  { country: "Trinidad and Tobago", timeZone: "America/Port_of_Spain" },
  { country: "Tunisia", timeZone: "Africa/Tunis" },
  { country: "Turkey", timeZone: "Europe/Istanbul" },
  { country: "Turkmenistan", timeZone: "Asia/Ashgabat" },
  { country: "Uganda", timeZone: "Africa/Kampala" },
  { country: "Ukraine", timeZone: "Europe/Kyiv" },
  { country: "United Arab Emirates", timeZone: "Asia/Dubai" },
  { country: "United Kingdom", timeZone: "Europe/London" },
  { country: "United States", timeZone: "America/New_York" },
  { country: "Uruguay", timeZone: "America/Montevideo" },
  { country: "Uzbekistan", timeZone: "Asia/Tashkent" },
  { country: "Vanuatu", timeZone: "Pacific/Efate" },
  { country: "Vatican City", timeZone: "Europe/Vatican" },
  { country: "Venezuela", timeZone: "America/Caracas" },
  { country: "Vietnam", timeZone: "Asia/Ho_Chi_Minh" },
  { country: "Yemen", timeZone: "Asia/Aden" },
  { country: "Zambia", timeZone: "Africa/Lusaka" },
  { country: "Zimbabwe", timeZone: "Africa/Harare" }
];


const App = () => {
  const [time, setTime] = useState(moment())
  useEffect(()=>{
   const interval=  setInterval(()=>{
      setTime(moment())
    },1000)
    return ()=>{
      clearInterval(interval)
    }
  }, [])
  return (
    <div className="bg-gradient-to-r from-rose-700 via-slate-700 to-blue-700 min-h-screen">
        <div className="w-9/12 mx-auto py-12">
          <h1 className="text-4xl text-center font-bold text-white">Worlds, Timer</h1>
          <div className="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-10 mt-10">
              {countries.map((item,idx)=>(
                <div className="bg-white  rounded-lg p-8 hover:shadow-red-500 shadow-2xl cursor-pointer hover:scale-110 duration-400" key={idx}>
                  <h1 className="text-2xl  font-bold text-rose-500 border-b-3 pb-2 border-b-blue-700">{item.country}</h1>
                  <h1 className=" text-3xl sm:text-2xl md:text-3xl lg:text-4xl xl:text-4xl  mt-4 font-semibold text-gray-700">
                    {
                      time.tz(item.timeZone).format('hh:mm:ss A')
                    }
                  </h1>
                </div>
              ))
              }
          </div>
        </div>
    </div>
  );
};

export default App;
